name: Deploy to IPFS

permissions:
  contents: read
  pull-requests: write
  statuses: write

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8 # Or specify a different version like 'latest' or a range
          # Optional: You can also specify the Node.js version if needed
          # node-version: 18

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm build

      - name: Deploy to IPFS
        uses: ipfs/ipfs-deploy-action@v1
        id: deploy
        with:
          path-to-deploy: dist # Change this to your build output directory
          kubo-api-url: ${{ secrets.KUBO_API_URL }}
          kubo-api-auth: ${{ secrets.KUBO_API_AUTH }}
          github-token: ${{ github.token }}

      - name: Deploy to IPNS
        run: curl -u ${{ secrets.KUBO_IPNS_AUTH }} -X POST "${{ secrets.KUBO_IPNS_URL }}/api/v0/name/publish?arg=${{ steps.deploy.outputs.cid }}&key=misaka"
